/**
 * Credit-use estimates for the UI ("Opus ~N credits/hr", per-voice cost lines).
 * Generated by the SAME pricing code that bills (meter.ts), so an estimate can
 * never drift from a real charge; only the assumed usage profile can be wrong,
 * which is what the pre-launch validation bead is for.
 *
 * The profile below was SEEDED FROM ONE MEASURED SESSION: ~50 minutes with
 * history caching on, ~33 facilitator turns, ~2,700 output tokens. Input runs
 * ~45:1 over output and most of it is cache READS (~0.1x), so cache pricing,
 * not output, drives cost. Order-of-magnitude (±~35%); the shape is the
 * durable part.
 *
 * Calibration against the admin per-hour report (Aug 2026, ~35 hours, still
 * dominated by one returning user, so "measured for that practice style", not
 * "typical"; re-estimate as the account mix widens, meditation-pal-bv9p):
 *   - turns matched (40.9/hr measured vs 39.6 assumed): left alone.
 *   - sttSeconds reseeded 240 → 1,000: billed STT held at ~20-25 min/hr in
 *     both looks. Talking vs VAD padding is still meditation-pal-0uw7's
 *     question, but the BILLED figure is what the badge should predict.
 *   - TTS band reseeded down (TTS_CHAR_PROFILES): measured cloud-voice
 *     sessions ran ~1k-6.2k chars, all under the old 10k "typical".
 *   - LLM token fields left at the seed: per-model samples are too small and
 *     track user style.
 *
 * The utility LLM (Haiku via buildUtilityProvider, plus the recap model)
 * is carried as its own flat leg, UTILITY_CREDITS_PER_HOUR below - it rides
 * every HOSTED session regardless of which model the badge names
 * (meditation-pal-nrj6), so it belongs in the composed session estimate, not
 * in any one badge.
 */

import type { SessionUsage } from '@aloud/core/facilitation';
import type { ProviderId } from '../contract.js';
import { priceSession, priceSttSeconds, usdToCredits } from './meter.js';
import { DEFAULT_STT_MODEL, allowedModels, ttsRateFor } from './providers.js';
import { CURATED_VOICES, type TtsProvider } from '../providers/voice-catalog.js';

/** Representative ~50-min session, history-caching ON. See file header. */
export const TYPICAL_SESSION_MINUTES = 50;

export const TYPICAL_SESSION: SessionUsage = {
    llmCalls: 33,
    llmTokensIn: 4_000, // fresh (uncached) user text across turns
    llmTokensOut: 2_700, // facilitator speech (~10k chars)
    llmCacheRead: 115_000, // re-sent prefix, cached at ~0.1x
    llmCacheCreation: 7_500, // unique content written to cache once
    sttSeconds: 1_000, // ~17 min billed audio per 50-min session (~20 min/hr)
    ttsChars: 10_000, // facilitator speech, if spoken by cloud TTS
};

/**
 * TTS chars per ~50-min session is a band, not a number: driven by facilitator
 * verbosity, how much the user shares (the facilitator mirrors length), and the
 * model (smaller open models run chattier; Claude models stay terser at the same
 * setting), so the UI shows a RANGE per voice, not a worst case (calibration
 * in the file header).
 *
 * LANGUAGE (meditation-pal-c3a0.4): these profiles are English-calibrated, and
 * zh sessions deliberately reuse them unadjusted. Measured over the parallel
 * canned pools (same content in both languages, src/facilitation/language.ts,
 * 2026-08-31): zh runs ~0.35x the characters of the same English content, and
 * Azure's bill-each-CJK-char-twice rule brings the BILLED count to ~0.69x
 * English. So an en-calibrated estimate OVERSTATES a zh session by ~1.45x -
 * conservative, never an under-bill - while the meter itself stays exact (the
 * TTS route prices the real billed chars per synthesis). Revisit with real zh
 * session telemetry (usage records carry billed chars) before shaving the
 * estimate.
 */
export const TTS_CHAR_PROFILES = {
    spacious: 1_200, // terse model / low verbosity / lots of held silence
    typical: 3_500, // mid of the measured band
    engaged: 7_500, // chattiest measured voice-hour, plus headroom
} as const;

export type TtsProfile = keyof typeof TTS_CHAR_PROFILES;

/**
 * Azure bills the SSML markup, not just the text (providers/tts.azureBilledChars),
 * and the sentence-chunked bridge (ui streaming-tts) synthesizes one sentence
 * per request - so a styled voice pays its express-as tags on EVERY sentence.
 * Fold that into the shown estimate or a styled voice reads ~40% cheaper than
 * it bills. The sentence length is eyeballed from meditation transcripts
 * (short lines; shorter sentences make the overhead worse, so this leans low
 * to stay conservative). paceBias voices pay the smaller prosody tag instead
 * (styled voices never get prosody - routes/tts.effectiveRate).
 */
const AZURE_AVG_SENTENCE_CHARS = 80;
const AZURE_STYLE_TAG_CHARS = '<mstts:express-as style="softvoice">'.length + '</mstts:express-as>'.length;
const AZURE_PROSODY_TAG_CHARS = '<prosody rate="1.15">'.length + '</prosody>'.length;

export function azureSsmlOverheadFactor(v: {
    provider: TtsProvider;
    style?: string;
    paceBias?: number;
}): number {
    if (v.provider !== 'azure') return 1;
    if (v.style) return 1 + AZURE_STYLE_TAG_CHARS / AZURE_AVG_SENTENCE_CHARS;
    if (v.paceBias) return 1 + AZURE_PROSODY_TAG_CHARS / AZURE_AVG_SENTENCE_CHARS;
    return 1;
}

const PER_HOUR = 60 / TYPICAL_SESSION_MINUTES;

function round1(n: number): number {
    return Math.round(n * 10) / 10;
}

/** A per-session provider cost as $/hr, for the estimates' costUsd fields. */
function usdPerHour(usdPerSession: number): number {
    return round1(usdPerSession * PER_HOUR * 100) / 100;
}

/**
 * Per-hour credits for a per-session figure, at 2dp. UNROUNDED to whole credits
 * on purpose: rounding belongs at the badge (ui/credit-rate.ts rateUnits), once,
 * so legs stay addable. Rounding here too meant a voice badge and the session
 * pill disagreed - the badge floored 3.8 to "3☁️" while the pill summed the 3.8.
 */
function creditsPerHour(creditsPerSession: number): number {
    return Math.round(creditsPerSession * PER_HOUR * 100) / 100;
}

export interface LegEstimate {
    creditsPerSession: number;
    creditsPerHour: number;
    /** Underlying provider cost per hour (credits debit at cost). For
     *  transparency / denomination tuning. */
    costUsdPerHour: number;
}

export interface ModelEstimate extends LegEstimate {
    provider: ProviderId;
    model: string;
}

/** Credits/hr for a leg across the TTS char band. */
export interface CreditBand {
    spacious: number;
    typical: number;
    engaged: number;
}

export interface VoiceEstimate {
    voiceId: string;
    label: string;
    /** Credits/hr at each point in the talk band. Local voices are all 0. */
    creditsPerHour: CreditBand;
    /** Underlying provider cost $/hr at "typical", for denomination tuning. */
    costUsdPerHourTypical: number;
}

/** LLM-only credits for the typical session (zero STT/TTS, those are separate
 *  legs the UI composes). */
export function estimateModels(): ModelEstimate[] {
    const llmOnly: SessionUsage = { ...TYPICAL_SESSION, sttSeconds: 0, ttsChars: 0 };
    return allowedModels().map((m) => {
        const cost = priceSession(m.provider, m.model, llmOnly);
        return {
            provider: m.provider,
            model: m.model,
            creditsPerSession: cost.credits,
            creditsPerHour: creditsPerHour(cost.credits),
            costUsdPerHour: usdPerHour(cost.providerCostUsd),
        };
    });
}

/** The background-assistant leg of a HOSTED session: Haiku for the silence
 *  classifiers, noting labels, and end-of-session summary, and the `utility`
 *  model (providers.ts) for the in-session recap refresh (ui/views/session.ts
 *  buildUtilityProvider / buildRecapProvider). Metered only when the
 *  facilitation provider is 'aloud' - BYOK Anthropic runs Haiku on the user's
 *  own key, claude_proxy on their subscription, and everything else reuses the
 *  facilitation model - so the client adds this to the composed estimate only
 *  for aloud-cloud sessions. Aug 2026 telemetry measured Haiku at ~0.3 cr/hr
 *  over effectively all hours, recap included before it moved off Haiku, so
 *  0.3 leaves a little headroom. Not per-badge: the same flat leg whichever
 *  facilitation model is picked (nrj6). */
export const UTILITY_CREDITS_PER_HOUR = 0.3;

/** Cloud STT leg for a hosted model (default: DEFAULT_STT_MODEL), priced through the same meter code that bills. */
export function estimateStt(model: string = DEFAULT_STT_MODEL): LegEstimate {
    const cost = priceSttSeconds(TYPICAL_SESSION.sttSeconds, model);
    return {
        creditsPerSession: cost.credits,
        creditsPerHour: creditsPerHour(cost.credits),
        costUsdPerHour: usdPerHour(cost.providerCostUsd),
    };
}

/** Typical-profile credits/hr for a voice id: the "how fast does this burn my
 *  credits" number the picker shows, computed from the SAME rate the meter bills
 *  with (so it can't drift). Azure's per-sentence SSML tags are folded in via
 *  azureSsmlOverheadFactor. Two decimals, unrounded - see creditsPerHour(). */
export function voiceCreditsPerHourTypical(
    provider: TtsProvider,
    voiceId: string,
    treatment?: { style?: string; paceBias?: number }
): number {
    const overhead = azureSsmlOverheadFactor({ provider, ...treatment });
    const usdPerHour =
        TTS_CHAR_PROFILES.typical * overhead * ttsRateFor(provider, voiceId) * PER_HOUR;
    return Math.round(usdToCredits(usdPerHour) * 100) / 100;
}

/** A free local voice line (device/OS speechSynthesis). Bills zero, shown so the
 *  picker can contrast "free" against the cloud options. */
function freeVoice(voiceId: string, label: string): VoiceEstimate {
    return {
        voiceId,
        label,
        creditsPerHour: { spacious: 0, typical: 0, engaged: 0 },
        costUsdPerHourTypical: 0,
    };
}

function voiceEngineLabel(v: { provider: TtsProvider; providerVoiceId: string; tier: string }): string {
    if (v.provider === 'openai') return 'OpenAI gpt-4o-mini-tts';
    if (v.provider === 'azure') return v.providerVoiceId.includes('DragonHD') ? 'Azure DragonHD' : 'Azure Neural';
    return v.tier === 'value' ? 'Google Neural2' : 'Google Chirp3-HD';
}

/**
 * Per-voice TTS leg, as a band across the talk profile. Covers only the voices a
 * user can ACTUALLY pick: free local engines plus the curated cloud voices
 * (voice-catalog.ts), each priced through the meter's own rate authority
 * (providers.ttsRateFor), so a shown line can't drift from the real charge.
 *
 * Engines we may wire later (meditation-pal-b7i) are absent rather than
 * advertised at a rate the server can't deliver: Google Standard ($4/1M) is a
 * one-line catalog add; off-roster candidates are Unreal Speech (~$8/1M), Hume
 * Octave (~$7.60/1M), Deepgram Aura ($15/1M), and self-hosted Kokoro (~$0.70/1M,
 * but breaks the stateless proxy).
 */
export function estimateVoices(): VoiceEstimate[] {
    const free = [
        freeVoice('browser-default', 'Device voice (free)'),
        freeVoice('os-premium', 'System premium voice (free)'),
    ];
    const cloud = CURATED_VOICES.map((v): VoiceEstimate => {
        const rate = ttsRateFor(v.provider, v.providerVoiceId) * azureSsmlOverheadFactor(v);
        const perHour = (chars: number): number => creditsPerHour(usdToCredits(chars * rate));
        return {
            voiceId: v.providerVoiceId,
            label: `Cloud voice - ${v.name} (${voiceEngineLabel(v)})`,
            creditsPerHour: {
                spacious: perHour(TTS_CHAR_PROFILES.spacious),
                typical: perHour(TTS_CHAR_PROFILES.typical),
                engaged: perHour(TTS_CHAR_PROFILES.engaged),
            },
            costUsdPerHourTypical: usdPerHour(TTS_CHAR_PROFILES.typical * rate),
        };
    });
    return [...free, ...cloud];
}
