/**
 * Credit-use estimates for the UI ("Opus ~N credits/hr", per-voice cost lines).
 * Generated by the SAME pricing code that bills (meter.ts), so an estimate can
 * never drift from a real charge; only the assumed usage profile can be wrong,
 * which is what the pre-launch validation bead is for.
 *
 * The profile below is SEEDED FROM ONE MEASURED SESSION: a ~50-minute practice
 * (emotions + parts + compassionate, high verbosity, full context) with HISTORY
 * CACHING ON:
 *   - ~33 facilitator LLM turns; output ~2,700 tokens (~10k chars of speech).
 *   - Full transcript re-sent each turn, but with prefix caching the bulk
 *     (~115k) is cache-READS at ~0.1x; only new user text is fresh input, and
 *     each turn's new content is a one-time cache CREATION.
 *   - Input:output volume is ~45:1, so cache pricing, not output, drives cost.
 * One data point, so these are order-of-magnitude (±~35%). Refine as telemetry
 * accumulates; the shape (heavy cached input, modest output) is the durable part.
 */

import type { SessionUsage } from '@aloud/core/facilitation';
import type { ProviderId } from '../contract.js';
import { priceSession, priceSttSeconds, usdToCredits } from './meter.js';
import { DEFAULT_STT_MODEL, allowedModels, sttPricingFor, ttsRateFor } from './providers.js';
import { CURATED_VOICES, type TtsProvider } from '../providers/voice-catalog.js';

/** Representative ~50-min session, history-caching ON. See file header. */
export const TYPICAL_SESSION_MINUTES = 50;

export const TYPICAL_SESSION: SessionUsage = {
    llmCalls: 33,
    llmTokensIn: 4_000, // fresh (uncached) user text across turns
    llmTokensOut: 2_700, // facilitator speech (~10k chars)
    llmCacheRead: 115_000, // re-sent prefix, cached at ~0.1x
    llmCacheCreation: 7_500, // unique content written to cache once
    sttSeconds: 240, // ~4 min of actual user speech (VAD-segmented)
    ttsChars: 10_000, // facilitator speech, if spoken by cloud TTS
};

/**
 * TTS chars per ~50-min session is a band, not a number: driven by facilitator
 * verbosity, how much the user shares (the facilitator mirrors length), and the
 * model (smaller open models run chattier; Claude models stay terser at the same
 * setting). The measured 10k sits at "typical" (Gemma at default verbosity, an
 * engaged user). So the UI shows a RANGE per voice, not a worst case.
 */
export const TTS_CHAR_PROFILES = {
    spacious: 5_000, // terser model / low verbosity / lots of held silence
    typical: 10_000, // the measured session
    engaged: 16_000, // chatty session, long user shares mirrored back
} as const;

export type TtsProfile = keyof typeof TTS_CHAR_PROFILES;

const PER_HOUR = 60 / TYPICAL_SESSION_MINUTES;

function round1(n: number): number {
    return Math.round(n * 10) / 10;
}

export interface LegEstimate {
    creditsPerSession: number;
    creditsPerHour: number;
    /** Underlying provider cost per hour (credits debit at cost). For
     *  transparency / denomination tuning. */
    costUsdPerHour: number;
}

export interface ModelEstimate extends LegEstimate {
    provider: ProviderId;
    model: string;
}

/** Credits/hr for a leg across the TTS char band. */
export interface CreditBand {
    spacious: number;
    typical: number;
    engaged: number;
}

export interface VoiceEstimate {
    voiceId: string;
    label: string;
    /** Credits/hr at each point in the talk band. Local voices are all 0. */
    creditsPerHour: CreditBand;
    /** Underlying provider cost $/hr at "typical", for denomination tuning. */
    costUsdPerHourTypical: number;
}

/** LLM-only credits for the typical session (zero STT/TTS, those are separate
 *  legs the UI composes). */
export function estimateModels(): ModelEstimate[] {
    const llmOnly: SessionUsage = { ...TYPICAL_SESSION, sttSeconds: 0, ttsChars: 0 };
    return allowedModels().map((m) => {
        const cost = priceSession(m.provider, m.model, llmOnly);
        return {
            provider: m.provider,
            model: m.model,
            creditsPerSession: cost.credits,
            creditsPerHour: Math.ceil(cost.credits * PER_HOUR),
            costUsdPerHour: round1(cost.providerCostUsd * PER_HOUR * 100) / 100,
        };
    });
}

/** Cloud STT leg for a hosted model (default: the server-default
 *  gpt-4o-transcribe). STT is flat-priced (meter.ts priceSttSeconds), so the
 *  per-hour credits are read straight off the advertised rate table rather than
 *  re-derived through PER_HOUR — the float round-trip could ceil an exact 2.0
 *  up to 3. Billed and shown can't drift: both come from STT_MODEL_PRICING. */
export function estimateStt(model: string = DEFAULT_STT_MODEL): LegEstimate {
    const cost = priceSttSeconds(TYPICAL_SESSION.sttSeconds, model);
    return {
        creditsPerSession: cost.credits,
        creditsPerHour: sttPricingFor(model).creditsPerTypicalHour,
        costUsdPerHour: round1(cost.providerCostUsd * PER_HOUR * 100) / 100,
    };
}

/** Typical-profile credits/hr for a voice id: the "how fast does this burn my
 *  credits" number the picker shows, computed from the SAME rate the meter bills
 *  with (so it can't drift). One decimal. */
export function voiceCreditsPerHourTypical(provider: TtsProvider, voiceId: string): number {
    const usdPerHour = TTS_CHAR_PROFILES.typical * ttsRateFor(provider, voiceId) * PER_HOUR;
    return Math.round(usdToCredits(usdPerHour) * 10) / 10;
}

/** A free local voice line (device/OS speechSynthesis). Bills zero, shown so the
 *  picker can contrast "free" against the cloud options. */
function freeVoice(voiceId: string, label: string): VoiceEstimate {
    return {
        voiceId,
        label,
        creditsPerHour: { spacious: 0, typical: 0, engaged: 0 },
        costUsdPerHourTypical: 0,
    };
}

/**
 * Per-voice TTS leg, as a band across the talk profile. Covers only the voices a
 * user can ACTUALLY pick: free local engines plus the curated cloud voices
 * (voice-catalog.ts: Google Chirp3-HD/Neural2, OpenAI gpt-4o-mini-tts), each
 * priced through the meter's own rate authority (providers.ttsRateFor), so a
 * shown line can't drift from the real charge.
 *
 * Engines we may wire later (meditation-pal-b7i) are absent rather than
 * advertised at a rate the server can't deliver: Google Standard ($4/1M) is a
 * one-line catalog add; off-roster candidates are Unreal Speech (~$8/1M), Hume
 * Octave (~$7.60/1M), Deepgram Aura ($15/1M), and self-hosted Kokoro (~$0.70/1M,
 * but breaks the stateless proxy).
 */
function voiceEngineLabel(v: { provider: TtsProvider; tier: string }): string {
    if (v.provider === 'openai') return 'OpenAI gpt-4o-mini-tts';
    return v.tier === 'value' ? 'Google Neural2' : 'Google Chirp3-HD';
}

export function estimateVoices(): VoiceEstimate[] {
    const free = [
        freeVoice('browser-default', 'Device voice (free)'),
        freeVoice('os-premium', 'System premium voice (free)'),
    ];
    const cloud = CURATED_VOICES.map((v): VoiceEstimate => {
        const rate = ttsRateFor(v.provider, v.providerVoiceId);
        const perHour = (chars: number): number =>
            Math.ceil(usdToCredits(chars * rate) * PER_HOUR);
        return {
            voiceId: v.providerVoiceId,
            label: `Cloud voice - ${v.name} (${voiceEngineLabel(v)})`,
            creditsPerHour: {
                spacious: perHour(TTS_CHAR_PROFILES.spacious),
                typical: perHour(TTS_CHAR_PROFILES.typical),
                engaged: perHour(TTS_CHAR_PROFILES.engaged),
            },
            costUsdPerHourTypical:
                round1(TTS_CHAR_PROFILES.typical * rate * PER_HOUR * 100) / 100,
        };
    });
    return [...free, ...cloud];
}
