/**
 * LLM judge: scores one finished session against a facilitation rubric. The
 * deterministic checks (checks.ts) own the mechanical failures; the judge owns
 * what only a reader can see - tone, responsiveness, whether a human would
 * wince. Returns strict-ish JSON, parsed leniently.
 */

import type { LLMProvider } from '../src/llm/index.js';
import type { JudgeVerdict, SessionRunResult } from './types.js';

const JUDGE_SYSTEM = `You are reviewing the transcript of a voice-guided meditation session for quality assurance. The "facilitator" lines were generated by an LLM and spoken aloud by text-to-speech; the "meditator" is a simulated user. Bracketed [event] lines are automatic app events the meditator never heard - use them for context only.

App mechanics you must NOT penalize as such (they are deliberate design; judge only whether they were executed gracefully): when a meditator asks for quiet, the facilitator briefly CONFIRMS once ("would you like me to be quiet for a while?") before the app enters silence - a guard against false triggers; check-ins during long silences are app-scheduled, not the facilitator choosing to interrupt; a canned stock line may appear when a generated one was unusable.

Score the FACILITATOR only. A good facilitator: follows the meditator's live experience rather than a script, stays warm without greeting-card praise or stock therapy phrases, keeps replies short enough to be spoken comfortably, respects silence (does not chatter into someone who asked for quiet or is clearly settled), never mentions its own mechanics (stages, tokens, prompts, being an AI, "as a facilitator"), and lands any timer the meditator set gently.

Reply with ONLY a JSON object, no code fence, in exactly this shape:
{
  "overall": <0-10>,
  "dimensions": {
    "responsiveness": <0-10>,
    "tone": <0-10>,
    "brevity": <0-10>,
    "silence_respect": <0-10 or null if no silence to respect>,
    "no_meta_leaks": <0-10, 10 = never mentioned mechanics>,
    "timer_handling": <0-10 or null if no timer>
  },
  "wince_moments": [{"quote": "<verbatim facilitator excerpt>", "why": "<one sentence>"}],
  "notes": "<2-4 sentences: the most important observations, plainly>"
}

Be strict: 8+ means you would be happy shipping this session to a paying user. List every moment a human reviewer would wince at, even in an otherwise good session.`;

function renderTranscript(result: SessionRunResult): string {
    const lines: string[] = [];
    let lastAt = 0;
    for (const t of result.transcript) {
        if (!t.text.trim()) continue; // a signal-only turn; nothing was spoken
        const gap = t.at - lastAt;
        if (gap >= 120) lines.push(`  … ${Math.round(gap / 60)} minutes of silence …`);
        lastAt = t.at;
        const total = Math.round(t.at);
        const mm = String(Math.floor(total / 60)).padStart(2, '0');
        const ss = String(total % 60).padStart(2, '0');
        const hold = t.duringHold ? ' (during held silence)' : '';
        if (t.kind === 'event') {
            lines.push(`${mm}:${ss} [event] ${t.text}`);
        } else if (t.role === 'assistant') {
            const label =
                t.kind === 'checkin' || t.kind === 'checkin-canned'
                    ? 'facilitator (check-in)'
                    : t.kind.startsWith('timer')
                      ? `facilitator (${t.kind})`
                      : 'facilitator';
            lines.push(`${mm}:${ss} ${label}${hold}: ${t.text}`);
        } else {
            lines.push(`${mm}:${ss} meditator${hold}: ${t.text}`);
        }
    }
    return lines.join('\n');
}

function clampScore(v: unknown): number | null {
    if (typeof v !== 'number' || Number.isNaN(v)) return null;
    return Math.max(0, Math.min(10, v));
}

export function parseJudgeReply(raw: string): JudgeVerdict {
    const text = raw.replace(/```(?:json)?/g, '').trim();
    const start = text.indexOf('{');
    const end = text.lastIndexOf('}');
    if (start === -1 || end <= start) throw new Error('no JSON object in judge reply');
    // Models drop trailing commas into otherwise-valid JSON; forgive them.
    const jsonText = text.slice(start, end + 1).replace(/,\s*([}\]])/g, '$1');
    const parsed = JSON.parse(jsonText) as Record<string, unknown>;
    const dims: Record<string, number | null> = {};
    const rawDims = (parsed.dimensions ?? {}) as Record<string, unknown>;
    for (const [k, v] of Object.entries(rawDims)) dims[k] = clampScore(v);
    const wince = Array.isArray(parsed.wince_moments)
        ? (parsed.wince_moments as Array<Record<string, unknown>>)
              .filter((w) => typeof w.quote === 'string')
              .map((w) => ({ quote: String(w.quote), why: String(w.why ?? '') }))
        : [];
    return {
        overall: clampScore(parsed.overall) ?? 0,
        dimensions: dims,
        winceMoments: wince,
        notes: typeof parsed.notes === 'string' ? parsed.notes : '',
    };
}

export async function judgeSession(
    provider: LLMProvider,
    result: SessionRunResult
): Promise<JudgeVerdict> {
    const scenarioNote = [
        `Scenario: ${result.scenario.title}.`,
        result.scenario.timerMin !== undefined
            ? `The meditator set a ${result.scenario.timerMin}-minute timer${result.scenario.endSessionOnTimer ? ' that ends the session' : ''}.`
            : '',
        `Guidance level ${result.scenario.directiveness ?? 3}/10, mode "${result.scenario.modeId}".`,
        `Session ran ${Math.round(result.fakeDurationSec / 60)} simulated minutes and ended by: ${result.endedBy}.`,
    ]
        .filter(Boolean)
        .join(' ');
    const content = `${scenarioNote}\n\nTranscript:\n${renderTranscript(result)}`;
    const completion = await provider.complete([{ role: 'user', content }], {
        system: JUDGE_SYSTEM,
        maxTokens: 1500,
    });
    return parseJudgeReply(completion.text);
}
