#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────
# Regenerate every committed icon raster from the SVG sources:
#
#   assets/app-icon.svg            rounded dark tile   (desktop / launcher)
#   assets/app-icon-ios.svg        full-bleed opaque   (iOS + store listings)
#   assets/app-icon-android-fg.svg adaptive foreground (transparent)
#
# Each has a `-small` sibling with the same figure and ring strokes +22%.
# Anything rendered below SMALL_BELOW px comes from those instead: a hairline
# ring survives at 512 and turns into a smudge at 64, so the small end needs
# more weight to say the same thing. Keep each pair in sync.
#
# The Tauri bundle set (ts/src-tauri/icons/) is generated by
#   cd ts && npx tauri icon ../assets/app-icon.svg
# which only takes one source - so run that first, then this script, which
# re-renders that set's sub-512 files from the small sibling.
#
# Requires: rsvg-convert (librsvg), magick (ImageMagick), iconutil (macOS).
# ─────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

SMALL_BELOW=512

TILE="$ROOT/assets/app-icon.svg"
TILE_SMALL="$ROOT/assets/app-icon-small.svg"
FULL="$ROOT/assets/app-icon-ios.svg"
FULL_SMALL="$ROOT/assets/app-icon-ios-small.svg"
ANDROID_FG="$ROOT/assets/app-icon-android-fg.svg"
ANDROID_FG_SMALL="$ROOT/assets/app-icon-android-fg-small.svg"

for tool in rsvg-convert magick; do
    command -v "$tool" &>/dev/null || { echo "Error: $tool not found (brew install librsvg imagemagick)"; exit 1; }
done

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# render <big-source> <small-source> <pixels> <output>
render() {
    local src="$1"
    [ "$3" -lt "$SMALL_BELOW" ] && src="$2"
    rsvg-convert -w "$3" -h "$3" "$src" -o "$4"
}

echo "→ assets/aloud.png, assets/aloud.ico"
render "$TILE" "$TILE_SMALL" 512 "$ROOT/assets/aloud.png"
for size in 16 32 48 64 128 256; do
    render "$TILE" "$TILE_SMALL" "$size" "$TMP/ico_$size.png"
done
magick "$TMP/ico_16.png" "$TMP/ico_32.png" "$TMP/ico_48.png" \
       "$TMP/ico_64.png" "$TMP/ico_128.png" "$TMP/ico_256.png" "$ROOT/assets/aloud.ico"

echo "→ assets/store/play-store-icon-512.png (Play listing; alpha rejected)"
render "$FULL" "$FULL_SMALL" 512 "$TMP/play.png"
magick "$TMP/play.png" -background '#110d08' -alpha remove -alpha off "$ROOT/assets/store/play-store-icon-512.png"

echo "→ iOS app icon (Capacitor)"
IOS_ICON="$ROOT/ts/ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png"
render "$FULL" "$FULL_SMALL" 1024 "$TMP/ios.png"
magick "$TMP/ios.png" -background '#110d08' -alpha remove -alpha off "$IOS_ICON"

echo "→ Android launcher icons (Capacitor)"
RES="$ROOT/ts/android/app/src/main/res"
# foreground layer: 108dp adaptive canvas at each density
for entry in "mdpi 108" "hdpi 162" "xhdpi 216" "xxhdpi 324" "xxxhdpi 432"; do
    set -- $entry
    render "$ANDROID_FG" "$ANDROID_FG_SMALL" "$2" "$RES/mipmap-$1/ic_launcher_foreground.png"
done
# legacy (pre-API-26) launcher icons: the tile, and a circle-masked full-bleed
for entry in "mdpi 48" "hdpi 72" "xhdpi 96" "xxhdpi 144" "xxxhdpi 192"; do
    set -- $entry
    density="$1"; size="$2"; half=$((size / 2))
    render "$TILE" "$TILE_SMALL" "$size" "$RES/mipmap-$density/ic_launcher.png"
    render "$FULL" "$FULL_SMALL" "$size" "$TMP/round_$size.png"
    magick "$TMP/round_$size.png" \
        \( -size "${size}x${size}" xc:black -fill white -draw "circle $half,$half $half,0" -alpha copy \) \
        -compose CopyOpacity -composite "$RES/mipmap-$density/ic_launcher_round.png"
done

echo "→ Tauri bundle set: re-rendering sub-${SMALL_BELOW}px files from the small tile"
TAURI_ICONS="$ROOT/ts/src-tauri/icons"
if [ -d "$TAURI_ICONS" ]; then
    # Only the plain square renders - the android/ subdir has its own layered
    # sources and Tauri's own conventions, and nothing there ships to a store.
    while IFS= read -r png; do
        width="$(magick identify -format '%w' "$png")"
        [ "$width" -lt "$SMALL_BELOW" ] || continue
        rsvg-convert -w "$width" -h "$width" "$TILE_SMALL" -o "$png"
    done < <(find "$TAURI_ICONS" -maxdepth 1 -name '*.png'; find "$TAURI_ICONS/ios" -name '*.png' 2>/dev/null)
    # icon.ico is multi-size; rebuild it from the same ladder as assets/aloud.ico
    [ -f "$TAURI_ICONS/icon.ico" ] && cp "$ROOT/assets/aloud.ico" "$TAURI_ICONS/icon.ico"
else
    echo "  (skipped - run: cd ts && npx tauri icon ../assets/app-icon.svg)"
fi

echo "→ macOS .icns"
"$SCRIPT_DIR/generate-icon.sh" >/dev/null

if [ -f "$TAURI_ICONS/icon.icns" ]; then
    cp "$ROOT/assets/aloud.icns" "$TAURI_ICONS/icon.icns"
fi

echo "Done."
